### ISSUE TITLE
Create CosmosDB Socket.IO adapter

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/API#206]
This will eliminte the extra cost of having a Redis cache in addition to a CosmosDB account.

https://github.com/socketio/socket.io-adapter
https://github.com/learnboost/socket.io-redis

**Comment by tony-gutierrez** [comment]
Did you guys build this adapter? Care to share?

**Comment by dwhieb** [comment]
@tony-gutierrez Unfortunately not. It may still happen down the road, but it would be a while if it did. Sorry to disappoint.
