### ISSUE TITLE
how should permissions work?

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/API#3]
We can do permissions in a couple ways:
1. Add a new collection to the database called Permissions, that will store mappings of users and resources they have permissions for. Downside: Before you let a user retrieve any resources, you have to check in the Permissions collection to see whether the user has permission to access it (unless the resource is marked as public).
2. Include a `permissions` field in every resource. This would be an object containing the following fields: `public` (boolean), `viewers` (array), `contributors` (array), and `owners` (array). The arrays would be arrays of user IDs. Downside: When a user retrieves a resource from the database, they shouldn't be able to see the permissions object inside it (we don't want to expose user IDs to anybody). So we'd have to delete the permissions object from any resource before sending it (not such a big deal really).
3. Include a `permissions` field in every user object containing three fields: `viewer`, `contributor`, `owner`. Each would be an array of the resources that the user has permission to view, edit, or own respectively. Downside: before returning any resource, we'd have to check whether the user who requested it has permissions for it. This means making a request to the Users collection of the database.

Option 2 is the only one that doesn't require an extra database call.

**Comment by dwhieb** [comment]
@amundo Can you weigh in on this too?

**Comment by jmangel** [comment]
option 1 seems like the worst. Option 2 is good because you only make a call to 1 database. option 3 could also be good, though, because even though there could be an extra database call, if you find out that they don't have permission, you avoid having to retrieve the whole text (or item), which is probably a larger file transfer than the user. I'm happy with either, but leaning towards 3 because it seems a little bit nicer with its division of labor and avoiding wasteful file transfer. I'll throw my vote in with you though @dwhieb

**Comment by dwhieb** [comment]
Yeah I think 3 is best too. Here's how the flow would work:
- client authenticates the user, and receives an access token from the server
- client includes the access token with any subsequent requests to the server
- the server uses the access token to find out which user is requesting the resource, and checks the users database to see whether the user has permission to access it

So based on this, I think our permissions functions will be like this: `addPermission(user, resource, permissionType)`. For this one, we'll use add rather than upsert. We'll need add and delete functions.

For plurals, I'm thinking just `addPermissions(users, resources, permissionType)`, where both users and resources have to be arrays (but can be an array of just one). The `addPermission` function can probably just call the `addPermissions` function again. Sound okay to you?

**Comment by jmangel** [comment]
What would the access token include? Just a key that identifies the user? And then it's the server that calls the user database to check permissions, not the client itself? I guess that's more secure. Sounds good to me!
But then how will the addPermission actually work? It's the user itself asking to get permission, how do we decide whether he/she gets it?

**Comment by dwhieb** [comment]
The access token for us will just be the user ID, encrypted (technically it's the user ID plus a [salt](https://en.wikipedia.org/wiki/Salt_%28cryptography%29). When the token comes back to the server, I'll decrypt it on the server, then use it to find the user and check their permissions.

Correct - the server calls the user database and checks permissions. We don't want the client to have direct access to user objects. In order to add/delete/edit users, people have to go to the API website and register or edit or delete their profile.

I'm thinking we'll have 3 levels of permission: Owner, Contributor, and Viewer. Only Owners would be able to update permissions for a resource. A user is automatically made an Owner for any resources they create. They should also be able to transfer ownership (add a new Owner permission, then delete their own Owner permission, or downgrade themselves to a Contributor or Viewer). Contributors can edit but not change permissions. Viewers can only view.

We'll also have to deal with the fact that speakers in the database might have pseudonyms. I think in the cases where there are pseudonyms, only Owners and Contributors can see the speaker's real name. Viewers and other see the pseudonym.

I suppose we'll also want a `requestPermission` function too, but let's put that off for now. I'll make an issue for it.

By the way, I'll be using a standardized procedure for authentication called OAuth 2.0. Here's a short overview. We'll just be doing the Implicit Grant type for now: http://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified

**Comment by dwhieb** [comment]
Just realized: The other nice thing about option 3 is that, even though the _server_ has to make a second call to the database, the _client_ only has to make one call to the API.
