### ISSUE TITLE
add a testing framework

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/API#50]

**Comment by amundo** [comment]
I've used jasmine for what it's worth. There are headless "runners" for Jasmine but I've never messed with them; I just run them in the browser. Probably worth looking into a headless runner setup for the long term. (Except dom-related stuff, which is trickier.)

**Comment by dwhieb** [comment]
I think Jasmine is the way to go!

**Comment by dwhieb** [comment]
https://github.com/digitallinguistics/dlx-api/commit/f454dcaab940b31eef4256d640298233a4f5dc00 adds the Jasmine testing framework
